# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            LexLib
description:      'Books mentioned on the Lex Fridman Podcast'
url:              "https://lexlib.io"
baseurl:          ""
excerpt_separator: <!--more-->

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
    
paginate:         10
default_og_image: "/public/og-default.png"
item_list_schema_limit: 100
